// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://deobtjgmduxzhxstbejm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlb2J0amdtZHV4emh4c3RiZWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzY0NjMsImV4cCI6MjA2NTcxMjQ2M30.PgGgIuaMwo3UMWLLav5s_sgXP-bLMfh6PJ9zy2sJW_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);